name: rodillo_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Package - Service locator
  get_it: ^7.2.0
  # Package - Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.1
  # Package used to make http calls
  http: ^0.13.4
  # State Manager
  get: ^4.6.1
  # Package that allows us to use Google Fonts
  google_fonts: ^2.3.1
  # Package that allows us to store the jwt
  flutter_secure_storage: ^5.0.2
  # Package that implements icons
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
